---
title: "smFISH vs LoRNA proportions"
output: html_notebook
---

```{r}

library(MSnbase)
library(tidyverse)
library(camprotR)
```

```{r}
dlorna_proportions <- readRDS('../../../3_rna/notebooks/1_dlorna/2_lorna/4_proportional_localisation/results/proportions_per_rep.rds')$gene %>%
  filter(condition=='DMSO') %>%
  select(ensembl_gene_id=id, Membrane)
```



```{r}
dlorna <-  readRDS('../../../6_shiny_app/out/dlorna.rds')$gene$DMSO
```

```{r}
feature_data <- fData(dlorna) %>% select(gene_name) %>% tibble::rownames_to_column('ensembl_gene_id')
```

```{r}
stderr <- function(x, na.rm=FALSE) {
  if (na.rm) x <- na.omit(x)
  sqrt(var(x)/length(x))
}
```

```{r}
dlorna_proportions_summarised <- dlorna_proportions %>% merge(feature_data, by='ensembl_gene_id') %>%
  group_by(gene_name) %>%
  summarise(mean_proportion_lorna=mean(Membrane),
            sd_proportion_lorna=sd(Membrane),
            se_proportion_lorna=stderr(Membrane),
            n=length(Membrane))


```

```{r}
head(dlorna_proportions_summarised)
```


Here, we compare the membrane proportions obtained by LoRNA with ER proportions estimated from smFISH
```{r}
smFISH <- readxl::read_excel('./MACF1.DSTquantification.xlsx', sheet=1)[,1:6]

smFISH_summarised <- smFISH %>%
  mutate(RNA=toupper(RNA)) %>%
  filter(M2!='\\') %>%
  mutate(M2=as.numeric(M2)) %>%
  group_by(RNA) %>%
  summarise(mean_proportion_smfish=mean(M2),
            sd_proportion_smfish=sd(M2),
            se_proportion_smfish=stderr(M2),
            n=length(M2))
  
print(smFISH_summarised)
```


```{r}
compared_methods <- dlorna_proportions_summarised %>%
  mutate(RNA=toupper(gene_name)) %>%
  merge(smFISH_summarised, by='RNA')
  
print(compared_methods)
```
```{r}
library(ggrepel)
```

```{r}
to_plot_dlorna <- dlorna_proportions %>%
  merge(feature_data, by='ensembl_gene_id')  %>%
  mutate(RNA=toupper(gene_name)) %>%
  filter(RNA %in% unique(smFISH$RNA)) %>%
  select(RNA, 'proportion'=Membrane) %>%
  mutate(method='LoRRITo')

to_plot_smfish <- smFISH %>%
  select(RNA, 'proportion'=M2) %>%
  mutate(method='smFISH')

library(ggbeeswarm)

p <- bind_rows(to_plot_dlorna, to_plot_smfish) %>%
  ggplot(aes(method, proportion)) +
  geom_quasirandom(aes(fill=method), size=3, pch=21, colour='grey30') +
  stat_summary(colour='grey20', fun='mean', size=1, pch=8) +
  theme_camprot(base_family='sans', base_size=15, border=FALSE) +
  scale_fill_manual(values=get_cat_palette(7)[c(5,7)], name='') +
  facet_wrap(~RNA, nrow=1, strip.position="bottom") +
  theme(aspect.ratio=4/1, strip.background=element_blank(),
        axis.text.x=element_blank(), axis.ticks.x=element_blank(),
        axis.line.x=element_blank()) +
  xlab('') +
  geom_hline(yintercept=0, size=1) +
  scale_y_continuous(limits=c(0,1), expand=c(0,0)) +
  ylab('ER proportion')


print(p)
ggsave('./smFISH_vs_LoRNA.png', width=3.5, height=3.5)
ggsave('./smFISH_vs_LoRNA.pdf', width=3.5, height=3.5)
```

```{r}
readRDS('../../../3_rna/notebooks/1_dlorna/2_lorna/4_proportional_localisation/results/proportions_per_rep.rds')$gene %>%
  select(ensembl_gene_id=id, condition, Membrane) %>%
  merge(feature_data, by='ensembl_gene_id')  %>%
  mutate(RNA=toupper(gene_name)) %>%
  filter(RNA %in% unique(smFISH$RNA)) 
```


