---
title: "Proportions schematic"
output: html_notebook
---

```{r}
library(tidyverse)
library(camprotR)
```


Here, we create some toy data to visualise how the proportional localisation works

```{r}
mem_profile <- c(0.25,0.5,0.2,0.02,0.01,0.01,0.01,0)
cyt_profile <- c(0.01,0.05,0.01,0.02,0.01,0.18,0.5,0.22)
nuc_profile <- c(0.02,0.04,0.06,0.3,0.2,0.23,0.1,0.05)
sum(nuc_profile)
plot(nuc_profile)

profiles <- data.frame('Fraction'=rep(1:8, 3),
                       'Abundance'=c(mem_profile, cyt_profile, nuc_profile),
                       'Localisation'=rep(c('Membrane','Cytosol','Nucleus'), each=8))

profiles_wide <- pivot_wider(profiles, values_from='Abundance', names_from='Localisation')
```


```{r}
colours <- c(rev(get_cat_palette(2)), 'grey')

p1_alt <- ggplot(profiles, aes(Fraction, Abundance, group=Localisation, fill=Localisation)) +
  geom_area(alpha=1/3, colour='grey50', position='identity') +
  theme_camprot(border=FALSE, base_family='sans') +
  scale_fill_manual(values=colours) +
  theme(legend.position=c(0.5, 1))

p1 <- ggplot(profiles, aes(Fraction, Abundance, group=Localisation, colour=Localisation)) +
  geom_line(size=1/3, alpha=0.8) +
  theme_camprot(border=FALSE, base_family='sans') +
  scale_colour_manual(values=colours) +
  theme(legend.position=c(0.5, 1))

print(p1)
print(p1_alt)
```
```{r}
#ratios for cyt, mem, nuc
simulate_mix <- function(cyt, mem, nuc, add_noise=FALSE, mean=0.02, sd=0.01){
  if(!dplyr::near(cyt+mem+nuc,  1)) stop('cyt + mem + nuc must equal 1!')
  
  sim_profile <- (mem_profile*mem) + (cyt_profile*cyt) + (nuc_profile*nuc)
  if(add_noise){
    sim_profile <- sim_profile + rnorm(8, mean, sd)
    sim_profile <- sim_profile/sum(sim_profile)
  }
  return(sim_profile)
}

set.seed(0)

simulated_and_markers <- profiles_wide

simulated_and_markers$no_noise <- simulate_mix(.6, .3, .1,  add_noise=FALSE)
simulated_and_markers$low_noise <- simulate_mix(.6, .3, .1,  add_noise=TRUE)
simulated_and_markers$high_noise <- simulate_mix(.6, .3, .1,  add_noise=TRUE, mean=0.1, sd=0.05)

```

```{r}

simulated_and_markers %>% pivot_longer(cols=-c(Fraction, Membrane, Cytosol, Nucleus)) %>%
  ggplot(aes(Fraction, value, group=name, colour=name)) +
  geom_line(size=2) +
  theme_camprot(border=FALSE, base_family='sans') +
  ylab('Abundance')

p2 <- ggplot(simulated_and_markers, aes(Fraction, no_noise, group=1)) +
  geom_line(size=1) +
  theme_camprot(border=FALSE, base_family='sans') +
  ylab('Abundance')

print(p2)
```

```{r}
library(glmnet)

indep_var <- simulated_and_markers %>% select(Membrane, Cytosol, Nucleus) %>% as.matrix()

fit <- glmnet(indep_var,
              simulated_and_markers$no_noise,
              family='gaussian',
              lower.limits=0,
              lambda=0,
              alpha=0)

coefs <- coefficients(fit)[,1]
print(coefs)      
coefs[2:length(coefs)] <- coefs[2:length(coefs)]/sum(coefs[2:length(coefs)])
print(coefs*100)
```
```{r}
profile_mixes <- profiles
profile_mixes$Abundance <- profile_mixes$Abundance * rep(coefs[2:4], each=8)

p3 <- ggplot(profile_mixes, aes(Fraction, Abundance)) +
  geom_area(colour='grey50', aes(fill=Localisation), alpha=1/3) +
  #geom_line(data=simulated_and_markers, aes(y=no_noise), size=1) +
  theme_camprot(border=FALSE, base_family='sans') +
  scale_fill_manual(values=colours, guide=FALSE)

print(p3)
```

```{r, fig.height=15}
library(cowplot)

plot_grid(p1, p2, p3, ncol = 1, align = "v")

```

```{r, fig.width=12}
p1_updated <- p1_alt +
  theme_camprot(base_size=15, base_family='sans', border=FALSE) +
  scale_fill_manual(values=colours, name='') +
  theme(legend.position=c(0.5, 1)) +
  theme(axis.text=element_blank(), axis.title=element_blank(), axis.ticks=element_blank()) +
  ggtitle('Marker profiles\n') +
  theme(plot.title = element_text(hjust = 0.5), aspect.ratio=3/4,
        axis.line = element_line(colour = "grey30", size = 0.5)) +
  scale_x_continuous(expand=c(0,0)) +
  scale_y_continuous(expand=c(0,0), limits=c(0, 0.5))

p2_updated <- p2  +
  theme_camprot(base_size=15, base_family='sans', border=FALSE) +
  ggtitle('New profile\n(0.6 Cyt, 0.3 Mem, 0.1 Nuc)') +
  theme(plot.title = element_text(hjust = 0.5), aspect.ratio=3/4) +
  scale_x_continuous(expand=c(0,0), breaks=1:8) +
  scale_y_continuous(expand=c(0,0), limits=c(0, 0.5))

p3_updated <- p3 +
  theme_camprot(base_size=15, base_family='sans', border=FALSE) +
  theme(axis.text=element_blank(), axis.title=element_blank(), axis.ticks=element_blank()) +
  ggtitle('Reconstructed proportions\n') +
  theme(plot.title = element_text(hjust = 0.5), aspect.ratio=3/4) +
  scale_x_continuous(expand=c(0,0)) +
  scale_y_continuous(expand=c(0,0), limits=c(0, 0.5))

plot_grid(p2_updated, p1_updated, p3_updated, ncol = 3, align = "vh")

png('./proportions_schematic.png', width=15, height=5, units='in', res=400)
plot_grid(p2_updated, p1_updated, p3_updated, ncol = 3, align = "vh")
dev.off()

pdf('./proportions_schematic.pdf', width=15, height=5)
plot_grid(p2_updated, p1_updated, p3_updated, ncol = 3, align = "vh")
dev.off()

```

