---
title: "Compare classifications with HPA"
author:
  - name: "Tom Smith"
    affiliation: "Cambridge Centre for Proteomics"
date: "`r format(Sys.time(), '%d %B, %Y')`"
abstract: | 
  Here, we compare the protein subcellular localisation classification with HPA
output:
  pdf_document:
  html_notebook: default
geometry: margin=1in
fontsize: 11pt
---
```{r}
library(MSnbase)
library(pRolocdata)
library(dplyr)
library(tidyr)
library(camprotR)
library(ggplot2)
```

```{r}

dLOPIT <- readRDS('../../out/combined_protein_res_inc_bandle_loc.rds')$DMSO 
dLOPIT_loc <- fData(dLOPIT)[,'bandle_alloc',drop=FALSE] %>% filter(!is.na(bandle_alloc))
dLOPIT_loc$classification <- recode(dLOPIT_loc$bandle_alloc,
                                    'NUCLEOPLASM-1'='NUCLEUS',
                                    'NUCLEOPLASM-2'='NUCLEUS',
                                    'PROTEIN COMPLEX'='CYTOSOL',
                                    'RIBOSOME'='CYTOSOL',
                                    'MITOCHONDRION'='MITOCHONDRIA')
```

```{r}
HPA <- readRDS('../../../../1_external/19_HPA/out/hpa_allocations.rds')

```

Note that the HPA annotations do not all line up with the marker classes we are using in dLOPIT.
```{r}
table(HPA$allocation)
table(dLOPIT_loc$classification)
```
Below, we update the HPA annotations so that they match our marker classes. In some cases, e.g "Actin filaments" there is no equivalent in our marker class so we will simply ignore this classification
```{r}

HPA <- HPA %>%
  mutate(allocation_LOPIT_classes=recode(
    allocation,
    'Cytoplasmic bodies'='CYTOSOL',
    "Cytosol"="CYTOSOL",
    "Endoplasmic reticulum"="ER",
    "Golgi apparatus"="GOLGI",
    "Lysosomes"="LYSOSOME",
    "Mitochondria"="MITOCHONDRIA",
    "Nuclear bodies"="NUCLEUS",
    "Nuclear membrane"="NUCLEUS",
    "Nuclear speckles"="NUCLEUS",
    "Nucleoli fibrillar center"="NUCLEUS",
    "Nucleoli"="NUCLEUS",
    "Nucleoplasm"="NUCLEUS",
    "Nucleus"="NUCLEUS",
    "Peroxisomes"="PEROXISOME",
    "Plasma membrane"="PM")) %>%
  filter(allocation_LOPIT_classes %in% unique(dLOPIT_loc$bandle_alloc))

table(HPA$allocation_LOPIT_classes)
```


```{r}
dLOPIT_loc_vs_HPA <- HPA %>% filter(hpa_confidence %in% c('Approved')) %>%
  merge(dLOPIT_loc, by.y='row.names', by.x='uniprotswissprot', all.y=TRUE)
```

```{r}

dLOPIT_loc_vs_HPA_agreement <- dLOPIT_loc_vs_HPA %>%
  filter(classification!='Undefined', !is.na(allocation_LOPIT_classes)) %>%
  group_by(uniprotswissprot, classification) %>%
  summarise(agreement=length(intersect(allocation_LOPIT_classes, classification))>0)
```

```{r}
dLOPIT_loc_vs_HPA_agreement_summarised <- dLOPIT_loc_vs_HPA_agreement %>% group_by(classification, agreement) %>% tally() %>%
  pivot_wider(names_from=agreement, values_from=n)

dLOPIT_loc_vs_HPA_agreement %>%
  group_by(agreement) %>% tally() %>%
  pivot_wider(names_from=agreement, values_from=n) %>%
  mutate(fraction_TRUE=`TRUE`/(`TRUE`+`FALSE`))
```

```{r}
data(lopitdcU2OS2018)
data(hyperLOPITU2OS2018)
```

```{r}
table(fData(hyperLOPITU2OS2018)$final.assignment)

hLOPIT_loc <- fData(hyperLOPITU2OS2018)[,'final.assignment',drop=FALSE] %>% filter(!is.na(final.assignment))
hLOPIT_loc$classification <- recode(hLOPIT_loc$final.assignment,
                                    'GA'='GOLGI',
                                    'CHROMATIN'='NUCLEUS',
                                    'RIBOSOME 40S'='CYTOSOL',
                                    'RIBOSOME 60S'='CYTOSOL',
                                    'PROTEASOME'='CYTOSOL',
                                    'MITOCHONDRION'='MITOCHONDRIA')

  
table(hLOPIT_loc$classification )
```

```{r}
table(fData(lopitdcU2OS2018)$final.assignment)

dcLOPIT_loc <- fData(lopitdcU2OS2018)[,'final.assignment',drop=FALSE] %>% filter(!is.na(final.assignment))
dcLOPIT_loc$classification <- recode(dcLOPIT_loc$final.assignment,
                                    'GA'='GOLGI',
                                    'NUCLEUS/CHROMATIN'='NUCLEUS',
                                    'RIBOSOME'='CYTOSOL',
                                    'PROTEASOME'='CYTOSOL',
                                    'MITOCHONDRION'='MITOCHONDRIA')


table(dcLOPIT_loc$classification )
```





```{r}
table(HPA$hpa_confidence)
hpa_confidence_levels <- list('Approved', 'Supported', 'Enhanced', 'Uncertain')
names(hpa_confidence_levels) <- hpa_confidence_levels

lopits <- list(dcLOPIT_loc, hLOPIT_loc, dLOPIT_loc)
names(lopits) <- c('LOPIT-DC', 'hyperLOPIT', 'dLOPIT')
```


```{r}
lopits <- lapply(lopits, function(x) filter(x, !classification %in% c('unknown', 'Undefined')))
common_proteins <- Reduce('intersect', lapply(lopits, rownames))
print(length(common_proteins))
lopits_common <- lapply(lopits, function(x) x[common_proteins,])
```

```{r}

get_agreement_lopit_hpa <- function(hpa_loc, lopit_loc){
  lopitloc_vs_hpa <- hpa_loc %>%
    merge(lopit_loc, by.y='row.names', by.x='uniprotswissprot', all.y=TRUE)  
  
  lopitloc_vs_hpa_agreement <- lopitloc_vs_hpa %>%
  filter(!is.na(allocation_LOPIT_classes)) %>%
  group_by(uniprotswissprot, classification) %>%
  summarise(agreement=length(intersect(allocation_LOPIT_classes, classification))>0)
  
  lopitloc_vs_hpa_agreement %>%
    group_by(agreement, classification) %>% tally() %>%
    pivot_wider(names_from=agreement, values_from=n) %>%
    mutate("TRUE"=replace_na(`TRUE`, 0),
           "FALSE"=replace_na(`FALSE`, 0)) %>%
    mutate(fraction_TRUE=`TRUE`/(`TRUE`+`FALSE`),
           total=`TRUE`+`FALSE`)
}

get_all_lopit_vs_hpa <- function(lopits){
  all_lopit_vs_hpa <- lapply(hpa_confidence_levels, function(confidence_level){
    
    confidence_level_ix <- which(hpa_confidence_levels==confidence_level)
    keep_confidence_levels <- hpa_confidence_levels[1:confidence_level_ix]
  
    lopits %>% lapply(function(lopit_loc){
      HPA %>% filter(hpa_confidence %in% keep_confidence_levels) %>%
      get_agreement_lopit_hpa(lopit_loc)  
    }) %>% bind_rows(.id='LOPIT')
    
  }) %>% bind_rows(.id='confidence_level') %>%
    mutate(confidence_level=factor(confidence_level, levels=hpa_confidence_levels))
}


summarise_all_lopit_vs_hpa <- function(all_lopit_vs_hpa){
  all_lopit_vs_hpa %>%
    group_by(confidence_level, LOPIT) %>%
    summarise('TRUE'=sum(`TRUE`), 'FALSE'=sum(`FALSE`)) %>%
    mutate(fraction_TRUE=`TRUE`/(`TRUE`+`FALSE`),
           total=`TRUE`+`FALSE`)
}
```


```{r, warning=FALSE, message=FALSE}
all_lopit_vs_hpa <- get_all_lopit_vs_hpa(lopits)
all_lopit_vs_hpa_summarised <- summarise_all_lopit_vs_hpa(all_lopit_vs_hpa)

all_lopit_common_vs_hpa <- get_all_lopit_vs_hpa(lopits_common)
all_lopit_common_vs_hpa_summarised <- summarise_all_lopit_vs_hpa(all_lopit_common_vs_hpa)

```


```{r}

plot_all_lopit_vs_hpa_summarised <- function(all_lopit_vs_hpa_summarised){
  all_lopit_vs_hpa_summarised %>%
    filter(confidence_level!='Uncertain') %>%
    ggplot(aes(LOPIT, 100*fraction_TRUE)) +
    geom_bar(stat='identity', fill='grey80', colour=NA) + 
    facet_wrap(~confidence_level, nrow=1) +
    theme_camprot(border=FALSE, base_family='sans', base_size=15) +
    theme(strip.background=element_blank(), axis.text.x=element_text(angle=45, vjust=1, hjust=1)) +
    xlab('') +
    ylab('Agreement with HPA (%)') +
    ylim(0, 100*(max(all_lopit_vs_hpa_summarised$fraction_TRUE)*1.05)) + 
    geom_text(aes(y=100*fraction_TRUE/2, label=total), colour='grey20') +
    geom_text(aes(label=sprintf('%.0f', 100*fraction_TRUE, 0)), vjust=-0.2, colour='grey20')
}

p <- plot_all_lopit_vs_hpa_summarised(all_lopit_vs_hpa_summarised)
print(p)
ggsave('../../../../5_manuscript_figures/Figure_1/hpa/all_conf_levels.png', height=5, width=10)
ggsave('../../../../5_manuscript_figures/Figure_1/hpa/all_conf_levels.pdf', height=5, width=10)

p <- all_lopit_vs_hpa_summarised %>%
  filter(confidence_level=='Approved') %>%
  plot_all_lopit_vs_hpa_summarised() +
  theme(strip.text=element_blank())

print(p)
ggsave('../../../../5_manuscript_figures/Figure_1/hpa/Approved.png', height=5, width=5)
ggsave('../../../../5_manuscript_figures/Figure_1/hpa/Approved.pdf', height=5, width=5)



p <- plot_all_lopit_vs_hpa_summarised(all_lopit_common_vs_hpa_summarised)
print(p)
```
```{r, fig.height=10, fig.width=8}
plot_all_lopit_vs_hpa <- function(all_lopit_vs_hpa){
  all_lopit_vs_hpa %>%
      filter(confidence_level!='Uncertain') %>%
      ggplot(aes(LOPIT, 100*fraction_TRUE)) +
      geom_bar(stat='identity', fill='grey80', colour=NA) +
      facet_grid(classification~confidence_level) +
      theme_camprot(border=FALSE, base_family='sans', base_size=12) +
      theme(strip.background=element_blank(), axis.text.x=element_text(angle=45, vjust=1, hjust=1)) +
      xlab('') +
      ylab('Agreement with HPA (%)') +
      ylim(0, 100*(max(all_lopit_vs_hpa$fraction_TRUE)*1.1)) + 
      geom_text(aes(y=100*fraction_TRUE/2, label=total), colour='grey20')
}

plot_all_lopit_vs_hpa(all_lopit_vs_hpa)
plot_all_lopit_vs_hpa(all_lopit_common_vs_hpa)
```


